setwd("~/Dropbox/teaching/201901_ST242/r-code")
magazine <- read.table("data/magazine.txt", header=T)
attach(magazine)
age.c <- trunc(age/10)
table(gender,subs)
table(age.c,subs)
gender.1 <- ifelse(gender=="Male",1,0)
logistic.magazine <- glm(subs ~ gender.1 + age + socio + polit, family="binomial")
summary(logistic.magazine)
